name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Environment
        run: echo "Server IP is: ${{ secrets.SERVER_IP }}"

      - name: SSH into server & deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: deployer
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/deployer/modularWebworx/modular_Webworx
            git pull origin main

            # Deploy backend
            cd server
            npm install
            pm2 restart all

            # Deploy frontend
            cd ../client
            npm install
            npm run build
            sudo systemctl restart nginx
