name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy changes
        run: |
          ssh -o StrictHostKeyChecking=no deployer@66.179.190.150 <<EOF
          cd /home/deployer/modularWebworx/modular_Webworx
          git pull origin main

          # Deploy backend
          cd server
          npm install
          pm2 restart all

          # Deploy frontend
          cd ../client
          npm install
          npm run build

          # Restart Nginx (passwordless sudo required)
          sudo systemctl restart nginx
          EOF
