name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH Key to Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 66.179.190.150 >> ~/.ssh/known_hosts

    - name: SSH into Server and Pull Latest Code
      run: |
        ssh deployer@66.179.190.150 'cd ../../modularwebworx && git pull'

    - name: Install Client Dependencies
      run: |
        ssh deployer@66.179.190.150 'source ~/.nvm/nvm.sh && cd ../../modularwebworx/client && npm install'

    - name: Build Client
      run: |
        ssh deployer@66.179.190.150 'source ~/.nvm/nvm.sh && cd ../../modularwebworx/client && npm run build'

    - name: Install Server Dependencies
      run: |
        ssh deployer@66.179.190.150 'source ~/.nvm/nvm.sh && cd ../../modularwebworx/server && npm install'

    - name: Restart PM2
      run: |
        ssh deployer@66.179.190.150 'source ~/.nvm/nvm.sh && cd ../../modularwebworx/server && pm2 restart ecosystem.config.js'

    - name: Restart Nginx
      run: |
        ssh deployer@66.179.190.150 'sudo systemctl restart nginx'
